FROM ubuntu:latest

MAINTAINER brigzzy

#COPY ./hello-world /srv
WORKDIR /srv

RUN apt update && \
apt install -y nodejs npm && \
apt-get clean && \
npm install -g gatsby-cli

EXPOSE 8000
CMD gatsby telemetry --disable && gatsby develop --host=0.0.0.0
